# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calendar Frontend' do
  
  use_frameworks!

  pod 'Alamofire', '~> 4.7.2'
  pod 'SwiftyJSON', '~> 4.1.0'
  
  pod 'DatePickerDialog'

end
